//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lecture_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetail_ID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Order_ID { get; set; }
        public Nullable<int> Album_ID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Order Order { get; set; }
    }
}
