// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalC_.Migrations
{
    [DbContext(typeof(MedicalContext))]
    partial class MedicalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalC_.db.Models+Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Dr. Ana Beridze",
                            Specialization = "Cardiologist"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Dr. Giorgi Kapanadze",
                            Specialization = "Dermatologist"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Dr. Nino Tsintsadze",
                            Specialization = "Pediatrician"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Dr. Giorgi Tsintsadze",
                            Specialization = "Pediatrician"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Dr. Lela Gogua",
                            Specialization = "Pediatrician"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Dr. Levan Kharabadze",
                            Specialization = "Oncologist"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Dr. Tamta Meskhidze",
                            Specialization = "Gynecologist"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Dr. Beka Mchedlidze",
                            Specialization = "ENT"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Dr. Irina Tushurashvili",
                            Specialization = "Psychiatrist"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Dr. Archil Bregvadze",
                            Specialization = "Urologist"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Dr. Nato Kipiani",
                            Specialization = "Endocrinologist"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Dr. Irakli Chanishvili",
                            Specialization = "Radiologist"
                        },
                        new
                        {
                            Id = 13,
                            FullName = "Dr. Tea Geguchadze",
                            Specialization = "Rheumatologist"
                        },
                        new
                        {
                            Id = 14,
                            FullName = "Dr. Giorgi Baramidze",
                            Specialization = "Hematologist"
                        },
                        new
                        {
                            Id = 15,
                            FullName = "Dr. Maka Chelidze",
                            Specialization = "Immunologist"
                        });
                });

            modelBuilder.Entity("FinalC_.db.Models+Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1985, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lasha Qartvelishvili"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1992, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mariam Gelashvili"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Lika Metreveli"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Irakli Chikhladze"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1992, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Salome Dumbadze"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1987, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nika Tsereteli"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1994, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Keti Gogoladze"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1996, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Tornike Abashidze"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2001, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mariam Tvalavadze"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1995, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Luka Maisuradze"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1998, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nino Koberidze"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1986, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Giorgi Tchubinishvili"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1993, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Elene Sulaberidze"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2002, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Zura Kacharava"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1989, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Tamar Khutsishvili"
                        });
                });

            modelBuilder.Entity("FinalC_.db.Models+Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            Fee = 150m,
                            PatientId = 1,
                            VisitDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            Fee = 200m,
                            PatientId = 1,
                            VisitDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            Fee = 100m,
                            PatientId = 2,
                            VisitDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FinalC_.db.Models+Visit", b =>
                {
                    b.HasOne("FinalC_.db.Models+Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalC_.db.Models+Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("FinalC_.db.Models+Doctor", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("FinalC_.db.Models+Patient", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
